name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

permissions:
  contents: read

env:
  APP_NAME: tailwindcss-oxide
  NODE_VERSION: 20
  OXIDE_LOCATION: ./crates/node

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tailwind_version: ${{ steps.get-tag.outputs.tag }}
      daisyui_version: ${{ steps.get-daisyui.outputs.version }}
    steps:
      - name: Checkout FastHTML
        uses: actions/checkout@v4

      - name: Get latest v4 tag
        id: get-tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/tailwindlabs/tailwindcss/tags | jq -r '.[] | select(.name | startswith("v4")) | .name' | head -n1)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Clone Tailwind
        uses: actions/checkout@v4
        with:
          repository: tailwindlabs/tailwindcss
          ref: ${{ steps.get-tag.outputs.tag }}
          path: tailwindcss

      - name: Setup workspace and fix package references
        run: |
          # Create workspace files first
          echo '{
            "private": true,
            "workspaces": [
              "tailwindcss/crates/node",
              "tailwindcss/crates/node/npm/*",
              "tailwindcss/packages/*",
              "tailwindcss/playgrounds/*",
              "tailwindcss/integrations"
            ]
          }' > package.json

          echo 'packages:
            - "tailwindcss/crates/node"
            - "tailwindcss/crates/node/npm/*"
            - "tailwindcss/packages/*"
            - "tailwindcss/playgrounds/*"
            - "tailwindcss/integrations"' > pnpm-workspace.yaml

          # Use node to safely update package.json files
          node -e '
            const fs = require("fs");
            const path = require("path");
            
            function findPackageJsonFiles(dir) {
              let results = [];
              const files = fs.readdirSync(dir);
              for (const file of files) {
                const filePath = path.join(dir, file);
                const stat = fs.statSync(filePath);
                if (stat.isDirectory()) {
                  results = results.concat(findPackageJsonFiles(filePath));
                } else if (file === "package.json") {
                  results.push(filePath);
                }
              }
              return results;
            }

            const packageFiles = findPackageJsonFiles("tailwindcss");
            const replacements = {
              "@types/node": "^20.14.8",
              "lightningcss": "^1.26.0",
              "vite": "^6.0.0"
            };

            for (const file of packageFiles) {
              const content = JSON.parse(fs.readFileSync(file, "utf8"));
              let modified = false;
              
              ["dependencies", "devDependencies", "peerDependencies"].forEach(depType => {
                if (content[depType]) {
                  Object.entries(content[depType]).forEach(([pkg, version]) => {
                    if (version === "catalog:" && replacements[pkg]) {
                      content[depType][pkg] = replacements[pkg];
                      modified = true;
                    }
                  });
                }
              });
              
              if (modified) {
                fs.writeFileSync(file, JSON.stringify(content, null, 2) + "\n");
              }
            }
          '

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm environment
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          mkdir -p "$PNPM_HOME"
          export PATH="$PNPM_HOME:$PATH"
          pnpm --version

      - name: Setup Tailwind standalone
        run: |
          cd tailwindcss/packages/@tailwindcss-standalone
          mkdir -p .
          # Copy the patches directory if it exists
          if [ -d "../../../patches" ]; then
            cp -r ../../../patches ../../
          fi
          pnpm install --no-frozen-lockfile --ignore-scripts --prefer-offline || true
          pnpm add -D daisyui@beta

      - name: Modify standalone index
        run: |
          cd tailwindcss
          # Add daisyui to switch case
          sed -i '/case "@tailwindcss\/aspect-ratio":/a \ \ \ \ case "daisyui":\n \ \ \ \ \ \ return id' packages/@tailwindcss-standalone/src/index.ts
          # Add daisyui to load function
          sed -i '/return require("@tailwindcss\/aspect-ratio")/a \ \ } else if (id.endsWith("daisyui")) {\n \ \ \ \ return require("daisyui")' packages/@tailwindcss-standalone/src/index.ts

      - name: Get DaisyUI version
        id: get-daisyui
        run: |
          cd tailwindcss/packages/@tailwindcss-standalone
          DAISYUI_VERSION=$(pnpm list daisyui --json | jq -r '.[0].dependencies.daisyui.version')
          echo "version=$DAISYUI_VERSION" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    strategy:
      matrix:
        include:
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          # macOS
          - os: macos-latest
            target: x86_64-apple-darwin
            strip: strip -x
          - os: macos-latest
            target: aarch64-apple-darwin
            page-size: 14
            strip: strip -x
          # Android
          - os: ubuntu-latest
            target: aarch64-linux-android
            strip: ${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
          - os: ubuntu-latest
            target: armv7-linux-androideabi
            strip: ${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            strip: strip
            container:
              image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            strip: llvm-strip
            container:
              image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            strip: llvm-strip
            container:
              image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-zig
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            strip: aarch64-linux-musl-strip
            download: true
            container:
              image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            strip: strip
            download: true
            container:
              image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine

    name: Build ${{ matrix.target }} (OXIDE)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        if: ${{ matrix.container }}
        with:
          version: 8

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache oxide build
        uses: actions/cache@v4
        with:
          path: |
            ./oxide/target/
            ./crates/node/*.node
            ./crates/node/index.js
            ./crates/node/index.d.ts
          key: ${{ runner.os }}-${{ matrix.target }}-oxide-${{ hashFiles('./crates/**/*') }}

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Rust (Stable)
        if: ${{ matrix.download }}
        run: rustup default stable

      - name: Setup rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install dependencies
        run: |
          which pnpm || npm install -g pnpm
          pnpm install --ignore-scripts --filter=!./playgrounds/* --no-frozen-lockfile

      - name: Build release
        run: pnpm run --filter ${{ env.OXIDE_LOCATION }} build
        env:
          RUST_TARGET: ${{ matrix.target }}
          JEMALLOC_SYS_WITH_LG_PAGE: ${{ matrix.page-size }}

      - name: Strip debug symbols
        if: ${{ matrix.strip }}
        run: |
          # Use find to check for .node files more reliably
          if find "${{ env.OXIDE_LOCATION }}" -name "*.node" -type f | grep -q .; then
            ${{ matrix.strip }} ${{ env.OXIDE_LOCATION }}/*.node
          else
            echo "No .node files found to strip"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.target }}
          path: ${{ env.OXIDE_LOCATION }}/*.node

  release:
    runs-on: macos-14
    timeout-minutes: 15
    name: Build and release Tailwind CSS
    permissions:
      contents: write
    needs:
      - build
      - prepare

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache oxide build
        uses: actions/cache@v4
        with:
          path: |
            ./oxide/target/
            ./crates/node/*.node
            ./crates/node/index.js
            ./crates/node/index.d.ts
          key: ${{ runner.os }}-${{ matrix.target }}-oxide-${{ hashFiles('./crates/**/*') }}

      - name: Install dependencies
        run: pnpm --filter=!./playgrounds/* install

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.OXIDE_LOCATION }}

      - name: Move artifacts
        run: |
          cd ${{ env.OXIDE_LOCATION }}
          cp bindings-x86_64-pc-windows-msvc/* ./npm/win32-x64-msvc/
          cp bindings-aarch64-pc-windows-msvc/* ./npm/win32-arm64-msvc/
          cp bindings-x86_64-apple-darwin/* ./npm/darwin-x64/
          cp bindings-aarch64-apple-darwin/* ./npm/darwin-arm64/
          cp bindings-aarch64-linux-android/* ./npm/android-arm64/
          cp bindings-armv7-linux-androideabi/* ./npm/android-arm-eabi/
          cp bindings-aarch64-unknown-linux-gnu/* ./npm/linux-arm64-gnu/
          cp bindings-aarch64-unknown-linux-musl/* ./npm/linux-arm64-musl/
          cp bindings-armv7-unknown-linux-gnueabihf/* ./npm/linux-arm-gnueabihf/
          cp bindings-x86_64-unknown-linux-gnu/* ./npm/linux-x64-gnu/
          cp bindings-x86_64-unknown-linux-musl/* ./npm/linux-x64-musl/

      - name: Build Tailwind CSS
        run: |
          cd tailwindcss
          pnpm run build

      - name: Run pre-publish optimizations scripts
        run: |
          cd tailwindcss
          node ./scripts/pre-publish-optimizations.mjs

      - name: Upload Standalone Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tailwindcss-standalone
          path: tailwindcss/packages/@tailwindcss-standalone/dist/

      - name: Create template package
        run: |
          mkdir -p fasthtml-template/styles
          echo '@import "tailwindcss";' > fasthtml-template/styles/input.css
          echo '@plugin "daisyui";' >> fasthtml-template/styles/input.css
          cp Makefile fasthtml-template/
          cp main.py fasthtml-template/
          zip -r fasthtml-template.zip fasthtml-template/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ inputs.version }}
          body: |
            Updated to:
            - Tailwind CSS ${{ needs.prepare.outputs.tailwind_version }}
            - DaisyUI ${{ needs.prepare.outputs.daisyui_version }}
          files: |
            tailwindcss/packages/@tailwindcss-standalone/dist/sha256sums.txt
            tailwindcss/packages/@tailwindcss-standalone/dist/tailwindcss-linux-arm64
            tailwindcss/packages/@tailwindcss-standalone/dist/tailwindcss-linux-x64
            tailwindcss/packages/@tailwindcss-standalone/dist/tailwindcss-macos-arm64
            tailwindcss/packages/@tailwindcss-standalone/dist/tailwindcss-macos-x64
            tailwindcss/packages/@tailwindcss-standalone/dist/tailwindcss-windows-x64.exe
            fasthtml-template.zip